venv:
	python3 -m venv venv

install:
	. venv/bin/activate
	pip3 install -r requirements.txt

population: 
	cd population_count; python3 population.py

earthquakes: 
	cd natural_disasters/earthquakes; python3 earthquakes.py

hurricanes:
	cd natural_disasters/hurricanes; python3 hurricanes.py

tsunamis:
	cd natural_disasters/tsunamis; python3 tsunamis.py

vegetation:
	cd surface_properties/vegetation; python3 vegetation.py

wind:
	cd energy_strength/wind; python3 wind.py

solar:
	cd energy_strength/solar; python3 solar.py

map:
	python3 main.py

runall: population earthquakes hurricanes tsunamis vegetation wind solar map